AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template to create DynamoDB table for Calendar Events

Resources:
  CalendarEventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: CalendarEvents
      AttributeDefinitions:
        - AttributeName: UserId
          AttributeType: S
        - AttributeName: EventId
          AttributeType: S
        - AttributeName: StartTime
          AttributeType: S
      KeySchema:
        - AttributeName: UserId
          KeyType: HASH
        - AttributeName: EventId
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: StartTimeIndex
          KeySchema:
            - AttributeName: UserId
              KeyType: HASH
            - AttributeName: StartTime
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 4
            WriteCapacityUnits: 4
      ProvisionedThroughput:
        ReadCapacityUnits: 4
        WriteCapacityUnits: 4